### ISSUE TITLE
Ajouter utilisation LDAP 

### ISSUE THREAD

**Issue by Plumf** [YunoHost-Apps/yeswiki_ynh#2]
Ajouter durant l'installation l'extension de YesWiki pour utiliser le LDAP.

Extension : https://github.com/YesWiki/yeswiki-extension-loginldap

**Comment by Plumf** [comment]
Discussion à propos de l'intégration sur le forum ici : [forum.yunohost.org/yeswiki-ldap-ldap](https://forum.yunohost.org/t/yeswiki-informations-ldap-ldap-information/13357).
Plugin LDAP de YesWiki pas à jour, discussion sur le forum de YesWiki ici : [yeswiki.net/error-ldap-login](https://yeswiki.net/forum/?qa=2943/error-ldap-login)

**Comment by oncletom** [comment]
@Plumf le module a été mis à jour. Partant pour pairer avec toi pour faire aboutir cette fonctionnalité — elle m'intéresse :-D

**Comment by nils-van-zuijlen** [comment]
Bonjour, j'ai travaillé avec @mrflos sur le plugin LDAP et nous avons corrigé les soucis qu'il y avait pour l'intégration.
Ma PR ci-dessus devrait donc être fonctionnelle (chez mois ça marche), si quelqu'un peut tester l'update je lui en serais reconnaissant.
