### ISSUE TITLE
L'utilisation de mots de passe contenant &%/ n'est pas possible

### ISSUE THREAD

**Issue by nils-van-zuijlen** [YunoHost-Apps/yeswiki_ynh#22]
Le mot de passe n'est pas encodé dans la requête `local_curl` et il n'est du coup pas possible de mettre certains caractères spéciaux dedans, sous peine de se voir refuser l'accès ensuite.

Plus embêtant encore, il n'y a pas de message d'erreur quand ces caractères sont présents.

**Comment by mrflos** [comment]
J'ai pas testé mais apparemment il y a une option pour curl : https://stackoverflow.com/questions/296536/how-to-urlencode-data-for-curl-command

**Comment by mrflos** [comment]
Par contre, avec le ldap intégré, ce n'est peut etre plus la peine de demander de mot de passe, puisque c'est le ldap qui fait foi?
