### ISSUE TITLE
peut-on faire la mise a jour directement sous YesWiki ?

### ISSUE THREAD

**Issue by MX10-AC2N** [YunoHost-Apps/yeswiki_ynh#24]
Salut a tous, et merci beaucoup pour ce belle outils..
Je découvre tout juste YesWiki..
Je l'ai donc installé via Yunohost admin et maintenant lorsque je vais sur mon site YesWiki, j'ai la possibilité d'effectuer des mises à jours, seulement je ne suis pas sûr que l'on puisse lancer l'update directement dans YesWiki, ne faut-il pas attendre une update dispo dans Yunohost ??
Merci..

**Comment by jvayssiere** [comment]
J'ai essayé mais la mise à jour directement depuis YesWiki échoue à l'étape "Vérification des droits sur les fichiers". Il faut donc mettre à jour depuis l'interface ou la ligne de commande YunoHost. Mais là le problème est que le dernier package YunoHost pour YesWiki contient la version doryphore 2020-11-30-4, alors que la version la plus récente est doryphore 2021-03-25-19.

Mettre à jour [en utilisant la branche de test](https://forum.yunohost.org/t/yeswiki-wiki-that-is-quick-and-easy-to-use/11114) comme décrit ici n'apporte rien car la branche de test est au même niveau que la branche master.

**Comment by nils-van-zuijlen** [comment]
Non, effectivement, il n'est pas possible de faire les mises à jour du cœur de YesWiki depuis lui-même, pour conserver une cohérence avec la version ynh. Les installations et mises à jour d'extensions et thèmes sont possibles par contre.

La mise à jour vers la version 2021-04-06-2 est actuellement sur `testing` et arrive bientôt.
