### ISSUE TITLE
Restaurer sauvegarde casse propriétiaires de certains fichiers

### ISSUE THREAD

**Issue by jvayssiere** [YunoHost-Apps/yeswiki_ynh#30]
Bonsoir,

Si j'efface l'application yeswiki dans YH et que je la réinstalle à partir d'une sauvegarde précédente (le tout au travers de l'interface web admin de YH), les propriétaires de certains fichiers et répertoires ne sont pas restaurées correctement, ce qui casse par example la mise à jour des thèmes.

La permission initiale donnée par l'installation initiale est yeswiki:root, et après la restauration de la sauvegarde elle devient root:root, ce qui ne permet pas à l'utilisateur yeswiki de modifier les thèmes par exemple.

Les répertoires et fichiers suivants dans /var/www/yeswiki sont impactés:

- cache
- files
- themes
- tool
- wakka.config.php

Si je change les propriétaires à la main depuis la ligne de commande Linux tout rentre dans l'ordre.

Nous sommes sur YesWiki version 2020-11-30-4~ynh1 et YunoHost 4.1.8.

Merci!
Julien.

**Comment by nils-van-zuijlen** [comment]
Bonjour,

Merci pour le rapport de bug, le bug est corrigé depuis la version 2021-04-06-2, mais les scripts de restoration des versions précédentes sont sauvegardés dans la backup et ne sont pas corrigeables, malheureusement ici.

Pour corriger ce souci de permissions, il suffit de lancer la commande suivante avec le compte admin:
```bash
sudo chown -R yeswiki /var/www/yeswiki/{cache,files,themes,tools,wakka.config.php}
```

Dans le cas de multiples installations, l'adapter comme suit:
```bash
sudo chown -R yeswiki__2 /var/www/yeswiki__2/{cache,files,themes,tools,wakka.config.php}
```

Bonne journée,
Nils
