### ISSUE TITLE
Can't install on arm64 rpi 4, error at installation script

### ISSUE THREAD

**Issue by tr1p0p** [YunoHost-Apps/yeswiki_ynh#40]
On last yunohost version, on RPI 4 (4.3.4.2) Yeswiki don't install and show and error.

Here logs : https://paste.yunohost.org/raw/oquhemipev

It's seem it's a permission issues around write/read.

**Comment by mrflos** [comment]
thanks for your feedback, @tr1p0p , i'm the current maintainer of this package. I was not available when you went throught your issue, but you closed it, could you solve your database connection problem?  
I think we may still have some issues, about file access rights, i will try to release a version this or next friday.

Regards
