### ISSUE TITLE
Impossible de changer le titre du Wiki

### ISSUE THREAD

**Issue by Plumf** [YunoHost-Apps/yeswiki_ynh#7]
Il n'est pas possible de personnaliser le nom du wiki. Il reste bloqué à MyYunoHostWiki

**Comment by Plumf** [comment]
Changement du titre dans le fichier de cofiguration wakka.config.php (CLI)

Ajouter dans le script d'install 
`echo "$wiki_name" | sed 's/ /%20/g'` qui obligerait les espaces du nom de wiki à se transformer en %20

**Comment by yalh76** [comment]
it's now possible to choose the wiki name during install
