### ISSUE TITLE
Ical problem ?

### ISSUE THREAD

**Issue by tmaignan** [YunoHost-Apps/yeswiki_ynh#75]
### My YunoHost server

**Hardware:** VPS bought online.
**YunoHost version:** last update
**I have access to my server :** Through SSH & through the webadmin 
**Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?** : no 
**If yes, please explain:**
**If your request is related to an app, specify its name and version:** app v1.0~ynh1

### Description of my issue

Bonjour,

Quand je clique sur le ical pour synchroniser mon calendrier : 
Il m'envoie ce message d'erreur : 

```
""Error: Call to a member function getDateTimeWithRightTimeZone() on null in /var/www/yeswiki/tools/bazar/controllers/IcalFormatter.php:152\nStack trace:\n#0 /var/www/yeswiki/tools/bazar/controllers/IcalFormatter.php(115): YesWiki\\Bazar\\Controller\\IcalFormatter->getICALData()\n#1 [internal function]: YesWiki\\Bazar\\Controller\\IcalFormatter->YesWiki\\Bazar\\Controller\\{closure}()\n#2 /var/www/yeswiki/tools/bazar/controllers/IcalFormatter.php(114): array_map()\n#3 
/var/www/yeswiki/tools/bazar/controllers/IcalFormatter.php(70): YesWiki\\Bazar\\Controller\\IcalFormatter->formatToICAL()\n#4 /var/www/yeswiki/tools/bazar/controllers/ApiController.php(67): YesWiki\\Bazar\\Controller\\IcalFormatter->apiResponse()\n#5 [internal function]: YesWiki\\Bazar\\Controller\\ApiController->getAllFormEntries()\n#6 
/var/www/yeswiki/includes/YesWiki.php(1260): call_user_func_array()\n#7 /var/www/yeswiki/includes/YesWiki.php(1180): YesWiki\\Wiki->RunSpecialPages()\n#8 /var/www/yeswiki/index.php(18): YesWiki\\Wiki->Run()\n#9 {main}"
```

Avez-vous une idée de la raison ?

Salutations,

Thomas.

**Comment by mrflos** [comment]
problem solved in version 4.4.3~ynh1 , thank you for the feedback.
(c'est résolu avec la dernière version 4.4.3~ynh1, merci pour la remontée de bug)

**Comment by tmaignan** [comment]
Thank you !!!!!
