### ISSUE TITLE
Affichage des PDF ?

### ISSUE THREAD

**Issue by tmaignan** [YunoHost-Apps/yeswiki_ynh#79]
Bonjour,

Mes fichiers PDF ne s'affichent plus dans le yeswiki. Avez-vous le même soucis ? 

Par exemple : 

{{attach file="AISSE_EPARGNE.pdf" desc="AISSE_EPARGNE.pdf (28.6kB)" displaypdf="1" size="original" class=""}}

Donne un afficheur PDF en boucle sans aboutir : 

![image](https://github.com/YunoHost-Apps/yeswiki_ynh/assets/124516995/71e11da4-b1d5-4bb5-900b-75f4ef4238cc)

Cela marchait avant mais là cela ne marche plus. Peut-être suite à la dernière version de Yeswiki ynh-2 ?

Salutations,

Thomas.

**Comment by mrflos** [comment]
est ce que la console de debuggage du navigateur affiche des erreurs? Y aurait il une url publique ou l'on pourrait voir le bug?

**Comment by tmaignan** [comment]
Oui, il y a bien une erreur sur la console : 

`Le chargement du module à l’adresse « https://coop-utop.fr/yeswiki/javascripts/vendor/pdfjs-dist/build/pdf.mjs » a été bloqué en raison d’un type MIME interdit (« application/octet-stream »).`
`/yeswiki/javascripts/vendor/pdfjs-dist/web/viewer.mjs:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.`

L'adresse est visitable ici : https://coop-utop.fr/yeswiki/?PlanR1
