### ISSUE TITLE
Pbls upgrade sur somme de controle de extension-importer-1.0.0.zip

### ISSUE THREAD

**Issue by plabuse** [YunoHost-Apps/yeswiki_ynh#86]
Bonjour,
Petit pbls de mise à jour de yeswiki, sûrement à cause d'une mauvaise somme de contrôle sur le paquet extension-importer-1.0.0.zip
voir le paste `https://paste.yunohost.org/raw/teviwunuqi` , j'ai modifié le fichier `manifest.toml` pour adapter le hash, cela semble passer pour moi. J'essaie de faire la correction dans la branche `testing.
@+

**Comment by plabuse** [comment]
Je ne sais pas forker (je pensais pouvoir faire la modification online), donc ma modification est :

Je remplace la line sha256

```
[resources.sources.importerplugin]
url = "https://repository.yeswiki.net/doryphore/extension-importer-1.0.0.zip"
sha256 = "7c5e730b4724a991ae64fdf457b9ec6d0416621f7fecb38e5b7a73e36d22eb00"

```
par

```
[resources.sources.importerplugin]
url = "https://repository.yeswiki.net/doryphore/extension-importer-1.0.0.zip"
sha256 = "5e0312e5053588e45e5c415b43ca75d388bcf589d09fa6f09da1e3d7f5cfd755"
```
Quand il y aura un atelier, je passerai pour apprendre.
@+

**Comment by mrflos** [comment]
ok merci, je prend la PR!
