### ISSUE TITLE
Erreur 404 en cliquant sur le bouton "Se connecter"

### ISSUE THREAD

**Issue by jeey** [YunoHost-Apps/yeswiki_ynh#93]
### Describe the bug

On tombe sur une Erreur404 lorsqu'on clique sur le bouton "Se Connecter" dans le cas :
- d'une connexion via le SSO Yunohost
- d'un sous-domaine

### Context

- Hardware: Serveur dédié
- YunoHost version: [YunoHost](https://yunohost.org/) 11.2.12 (stable
- I have access to my server: SSH | webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
### Steps to reproduce

- Installer un yeswiki dans un sous-domaine
- Activer l'authentification via le SSO Yunohost

### Expected behavior

accéder directement à l'adresse permettant l'identification

### Exemple

Site où le problème se présente : [https://annyo.logaton.fr](https://annyo.logaton.fr)

**Comment by mrflos** [comment]
corrigé avec le parametre de configuration `yunohost_sso_domain`
